services:
  e2e-test:
    image: e2e-test-js:latest
    environment:
      WRITE_API_SERVER_BASE_URL: http://write-api-server-1:38080
      READ_API_SERVER_BASE_URL: http://read-api-server-1:38082
    depends_on:
      write-api-server-1:
        condition: service_started
      read-api-server-1:
        condition: service_started
