services:
  write-api-server-1:
    command: ["writeApi"]
    image: cqrs-es-example-js:latest
    container_name: write-api-server-js-1
    ports:
      - 38080:38080
    environment:
      AWS_REGION: ap-northeast-1
      API_HOST: "0.0.0.0"
      API_PORT: 38080
      API_ALLOW_ORIGINS: "http://localhost:38080,http://localhost:38082,http://localhost:8888"
      PERSISTENCE_JOURNAL_TABLE_NAME: journal
      PERSISTENCE_JOURNAL_AID_INDEX_NAME: journal-aid-index
      PERSISTENCE_SNAPSHOT_TABLE_NAME: snapshot
      PERSISTENCE_SNAPSHOT_AID_INDEX_NAME: snapshot-aid-index
      PERSISTENCE_SHARD_COUNT: 64
      PERSISTENCE_SNAPSHOT_INTERVAL: 10
      AWS_REGION_NAME: ${AWS_REGION}
      AWS_DYNAMODB_ENDPOINT_URL: http://localstack:4566
      AWS_DYNAMODB_ACCESS_KEY_ID: x
      AWS_DYNAMODB_SECRET_ACCESS_KEY: x
    depends_on:
      - localstack
      - dynamodb-admin
      - dynamodb-setup
  read-model-updater-1:
    command: [ "localRmu" ]
    image: cqrs-es-example-js:latest
    container_name: read-model-updater-js-1
    ports:
      - 38081:38081
    environment:
      AWS_REGION: ap-northeast-1
      API_HOST: "0.0.0.0"
      API_PORT: 8080
      AWS_REGION_NAME: ap-northeast-1
      AWS_DYNAMODB_ENDPOINT_URL: http://localstack:4566
      AWS_DYNAMODB_ACCESS_KEY_ID: x
      AWS_DYNAMODB_SECRET_ACCESS_KEY: x
      STREAM_JOURNAL_TABLE_NAME: journal
      STREAM_MAX_ITEM_COUNT: 32
      DATABASE_URL: mysql://ceer:ceer@mysql-local:3306/ceer
    depends_on:
      - localstack
      - dynamodb-admin
      - dynamodb-setup
    # restart: on-failure
  read-api-server-1:
    command: [ "readApi" ]
    image: cqrs-es-example-js:latest
    container_name: read-api-server-js-1
    ports:
      - 38082:38082
    environment:
      AWS_REGION: ap-northeast-1
      API_HOST: "0.0.0.0"
      API_PORT: 38082
      API_ALLOW_ORIGINS: "http://localhost:38080,http://localhost:38082,http://localhost:8888"
      DATABASE_URL: mysql://ceer:ceer@mysql-local:3306/ceer
    depends_on:
      - mysql
      - migration
      - write-api-server-1
      - read-model-updater-1
