name: CI
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Run lint"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm generate:backend
      - run: pnpm run lint:prettier
      - run: pnpm run lint:eslint
  test:
    runs-on: ubuntu-latest
    env:
      TEST_TIME_FACTOR: 10.0
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm generate:backend
      - run: pnpm run test
  e2e:
    runs-on: ubuntu-latest
    env:
      TEST_TIME_FACTOR: 10.0
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: pnpm docker:build-e2e-test
      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: cqrs-es-example-js
          outputs: type=docker
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: pnpm docker:compose-e2e-test
