name: CI
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Run lint"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm generate:backend
      - run: pnpm run lint:prettier
      - run: pnpm run lint:eslint
  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      TEST_TIME_FACTOR: 10.0
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm generate:backend
      - run: pnpm run test
  e2e:
    runs-on: ubuntu-latest
    needs: test
    env:
      TEST_TIME_FACTOR: 10.0
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm docker:build-e2e-test
      - run: pnpm docker:build
      - run: pnpm docker:compose-e2e-test
