name: CI
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Run lint"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: |
          pnpm install
          pnpm generate:backend
          pnpm run lint:prettier
          pnpm run lint:eslint
  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      TEST_TIME_FACTOR: 10.0
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: |
          pnpm install
          pnpm generate:backend
          pnpm run test
  e2e:
    runs-on: ubuntu-latest
    needs: test
    env:
      TEST_TIME_FACTOR: 10.0
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: |
          pnpm docker:build-e2e-test
          pnpm docker:build
          pnpm docker:compose-e2e-test
